apiVersion: v1
kind: Service
metadata:
  name: api-template-production-service
spec:
  type: LoadBalancer
  selector:
    app: api-template
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
